In [1]:
import pandas as pd
import os
import time
import warnings
warnings.filterwarnings('ignore')

t0=time.time()

srcFiles="../csvResults/"

assignee=pd.read_csv(os.path.join(srcFiles,"dfFinalDatasetAssigneeAddedAssignee.csv"),
                     usecols=['assignee_id','organization','patent','assignee','assignor','record_date'])

t1=time.time()
total=t1-t0
print("Total time is %4f" % (total/60), "mins\n")
print("The total number of unique assignee ids are:",len(assignee['assignee_id'].unique()))
print("The total number of unique patents are:",len(assignee['patent'].unique()),"\n")

display(assignee.info(null_counts=True),assignee.head())

Total time is 0.012924 mins

The total number of unique assignee ids are: 183558
The total number of unique patents are: 183185

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325990 entries, 0 to 325989
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   assignee_id   325990 non-null  object
 1   organization  325990 non-null  object
 2   patent        325990 non-null  object
 3   assignee      298426 non-null  object
 4   assignor      298426 non-null  object
 5   record_date   298426 non-null  object
dtypes: object(6)
memory usage: 14.9+ MB

None

,assignee_id,organization,patent,assignee,assignor,record_date
0,00000ce5-b13f-4a23-a8fb-c14409ad7b68,Audiobase,6327609,"Audiobase, Inc.","Ludewig, Carl",1999-09-22
1,00002c39-aad3-40df-ac8a-3356cd85af13,Nine 24,8479461,"Nine 24, Inc.","Carver, Kenneth R",2011-09-21
2,0001365f-96ee-48f7-a26d-3206e8ecc33b,Rogers Foods,5746024,"Rogers Foods, Inc.","Rice, Robert M.",1996-07-03
3,0001365f-96ee-48f7-a26d-3206e8ecc33b,Rogers Foods,5746024,Sensient Dehydrated Flavors Company,"Rogers Foods, Inc.",2005-10-25
4,0001d1a0-7e84-47d2-a477-cfa36731d3e6,Behr Innovations,7163196,Behr Innovations Llc,"Behr, Jerome P.",2005-10-04

In [2]:
t0=time.time()

pvData=pd.read_csv(os.path.join(srcFiles,"dfFinalDatasetAssigneeRemoved2022OutputResults.csv"))
pvData.rename(columns={'assignee':'assignee_id'},inplace=True)

t1=time.time()
total=t1-t0
print("Total time is %4f" % (total/60), "mins\n")
print("The total number of unique assignee ids are:",len(pvData['assignee_id'].unique()),"\n")

display(pvData.info(null_counts=True),pvData.head())

Total time is 0.006519 mins

The total number of unique assignee ids are: 130801

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130801 entries, 0 to 130800
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              130801 non-null  int64
 1   assignee_id     130801 non-null  object
 2   location        130801 non-null  object
 3   organization    130801 non-null  object
 4   city            130099 non-null  object
 5   state           130801 non-null  object
 6   latitude        130801 non-null  float64
 7   longitude       130801 non-null  float64
 8   dateFiled       130801 non-null  object
 9   dateGranted     130801 non-null  object
 10  dateFiledMin    130801 non-null  object
 11  dateGrantedMin  130801 non-null  object
 12  patentList      130801 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 13.0+ MB

None

,ID,assignee_id,location,organization,city,state,latitude,longitude,dateFiled,dateGranted,dateFiledMin,dateGrantedMin,patentList
0,0,00000ce5-b13f-4a23-a8fb-c14409ad7b68,c3f19987-16c7-11ed-9b5f-1234bde3cd05,Audiobase,Sausalito,CA,37.8590,-122.4850,9/22/1999,12/4/2001,9/22/1999,12/4/2001,['6327609']
1,3,0001d1a0-7e84-47d2-a477-cfa36731d3e6,dbb582b9-16c7-11ed-9b5f-1234bde3cd05,Behr Innovations,Northfield,MN,44.4582,-93.1612,10/5/2004,1/16/2007,10/5/2004,1/16/2007,['7163196']
2,4,0002f118-c333-4e04-9b5c-e6c7e7217c6d,e68d95a1-16c7-11ed-9b5f-1234bde3cd05,Maston,Zeigler,IL,37.8995,-89.0520,8/18/1992,8/10/1993,8/18/1992,8/10/1993,['6055791' '5233811']
3,5,00031f53-3651-4d2a-ab5e-160cdc614cbd,edb0ba3d-16c7-11ed-9b5f-1234bde3cd05,Ni Industries,Novi,MI,42.4806,-83.4755,10/28/1980,5/17/1983,10/28/1980,5/17/1983,['4531445' '4607445' '4689910' '4640142' '4633...
4,6,0003616d-001c-460d-a79f-893d34da4adf,ece0720e-16c7-11ed-9b5f-1234bde3cd05,Kenyon Technologies,Key Largo,FL,25.0870,-80.4472,4/30/2015,10/16/2018,4/30/2015,10/16/2018,['10098370' '10349668' '10645961']

In [3]:
t0=time.time()

# loads location dataset for businesses and individuals
addAssignee=assignee.merge(pvData,on=['assignee_id'],how='outer',indicator=True)
addAssignee1=addAssignee.loc[addAssignee['_merge']=='both'].copy()
addAssignee2=addAssignee1.iloc[:,0:18]
addAssignee2.rename(columns={'organization_y':'organization'},inplace=True)

addAssignee3=addAssignee2.iloc[:,[6,0,7,8,9,10,11,12,13,14,15,16,2,17,3,4,5]]

t1=time.time()
total=t1-t0
print("Total time is %4f" % (total/60), "mins\n")
print("The total number of unique assignee ids are:",len(addAssignee3['assignee_id'].unique()))
print("The total number of unique patents are:",len(addAssignee3['patent'].unique()),"\n")

display(addAssignee3.info(null_counts=True),addAssignee3.head())

Total time is 0.008932 mins

The total number of unique assignee ids are: 130798
The total number of unique patents are: 130592

<class 'pandas.core.frame.DataFrame'>
Int64Index: 235310 entries, 0 to 325988
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              235310 non-null  float64
 1   assignee_id     235310 non-null  object
 2   location        235310 non-null  object
 3   organization    235310 non-null  object
 4   city            234114 non-null  object
 5   state           235310 non-null  object
 6   latitude        235310 non-null  float64
 7   longitude       235310 non-null  float64
 8   dateFiled       235310 non-null  object
 9   dateGranted     235310 non-null  object
 10  dateFiledMin    235310 non-null  object
 11  dateGrantedMin  235310 non-null  object
 12  patent          235310 non-null  object
 13  patentList      235310 non-null  object
 14  assignee        216288 non-null  object
 15  assignor        216288 non-null  object
 16  record_date     216288 non-null  object
dtypes: float64(3), object(14)
memory usage: 32.3+ MB

None

,ID,assignee_id,location,organization,city,state,latitude,longitude,dateFiled,dateGranted,dateFiledMin,dateGrantedMin,patent,patentList,assignee,assignor,record_date
0,0.0,00000ce5-b13f-4a23-a8fb-c14409ad7b68,c3f19987-16c7-11ed-9b5f-1234bde3cd05,Audiobase,Sausalito,CA,37.8590,-122.4850,9/22/1999,12/4/2001,9/22/1999,12/4/2001,6327609,['6327609'],"Audiobase, Inc.","Ludewig, Carl",1999-09-22
4,3.0,0001d1a0-7e84-47d2-a477-cfa36731d3e6,dbb582b9-16c7-11ed-9b5f-1234bde3cd05,Behr Innovations,Northfield,MN,44.4582,-93.1612,10/5/2004,1/16/2007,10/5/2004,1/16/2007,7163196,['7163196'],Behr Innovations Llc,"Behr, Jerome P.",2005-10-04
5,4.0,0002f118-c333-4e04-9b5c-e6c7e7217c6d,e68d95a1-16c7-11ed-9b5f-1234bde3cd05,Maston,Zeigler,IL,37.8995,-89.0520,8/18/1992,8/10/1993,8/18/1992,8/10/1993,5233811,['6055791' '5233811'],"Maston Corporation, The","Odum, Thomas M.",1992-08-18
6,4.0,0002f118-c333-4e04-9b5c-e6c7e7217c6d,e68d95a1-16c7-11ed-9b5f-1234bde3cd05,Maston,Zeigler,IL,37.8995,-89.0520,8/18/1992,8/10/1993,8/18/1992,8/10/1993,5233811,['6055791' '5233811'],"Odum, Thomas M.","Maston Corporation, The, An Il Corp.",1996-01-23
7,4.0,0002f118-c333-4e04-9b5c-e6c7e7217c6d,e68d95a1-16c7-11ed-9b5f-1234bde3cd05,Maston,Zeigler,IL,37.8995,-89.0520,8/18/1992,8/10/1993,8/18/1992,8/10/1993,5233811,['6055791' '5233811'],Maston Corporation (A North Carolina Corp.),"Odum, Thomas M.",1996-09-09

In [4]:
# addAssignee3.to_csv("../csvResults/dfFinalDatasetAssigneeAddedAssigneeRemoved2022OutputResults.csv",index=False)